#! /usr/bin/sh
set -e

sysroot="$(rustc --print sysroot)"
machine="$(uname -m)"

if [ -z "${STD_TARGET}" ]; then
    STD_TARGET="$machine-unknown-linux-postgres"
fi

main() {
    case "$1" in
        build)
            setup_dir
            run_build
            ;;
        install)
            setup_dir
            run_build
            remove_rlibs
            copy_rlibs
            ;;
        clean)
            cargo clean
            remove_rlibs
            ;;
        help)
            print_help
            ;;
        *)
            print_help
            exit 1
            ;;
    esac
}

print_help() {
    echo "Usage: $0 help | build | clean | install"
}

setup_dir() {
    mkdir -p "${sysroot}"/lib/rustlib/"${STD_TARGET}"/lib
    cp --verbose ./"${STD_TARGET}.json" "${sysroot}"/lib/rustlib/"${STD_TARGET}"/target.json
}

copy_json() {
    cp --verbose ./"${STD_TARGET}.json" "${sysroot}"/lib/rustlib/"${STD_TARGET}"/target.json
}

remove_rlibs() {
    rm --force --verbose "${sysroot}"/lib/rustlib/"${STD_TARGET}"/lib/*.rlib
}

copy_rlibs() {
    cp --force --verbose target/${STD_TARGET}/release/deps/*.rlib "${sysroot}/lib/rustlib/${STD_TARGET}/lib"
}

run_build() {
    CARGO_PROFILE_RELEASE_DEBUG=0 \
    CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS=true \
    RUSTC_BOOTSTRAP=1 \
    RUSTFLAGS="-Cforce-unwind-tables=yes -Cembed-bitcode=yes -Aunused-unsafe" \
    __CARGO_DEFAULT_LIB_METADATA="nightlystd" \
    cargo build \
        --target "${STD_TARGET}" \
        -Zbinary-dep-depinfo \
        --release \
        --features "compiler-builtins-mem" \
        --manifest-path "library/test/Cargo.toml"
}

main "$@"
